{{/*

 Copyright 2026 The OKDP Authors.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

*/}}

{{- range .Values.saslUsers }}
{{- if not .username }}
{{- fail "saslUsers[].username is required" }}
{{- end }}
{{- if not .password }}
{{- fail (printf "saslUsers[].password is required for user '%s'" .username) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-creds" (include "kafka-strimzi-resources.fullname" $) .username }}
  labels:
    {{- include "kafka-strimzi-resources.labels" $ | nindent 4 }}
type: Opaque
stringData:
  password: {{ .password | quote }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: {{ .username }}
  labels:
    {{- include "kafka-strimzi-resources.labels" $ | nindent 4 }}
    strimzi.io/cluster: {{ include "kafka-strimzi-resources.fullname" $ }}
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: {{ printf "%s-%s-creds" (include "kafka-strimzi-resources.fullname" $) .username }}
          key: password
{{- end }}
